[project]
name = "masteringpytorch"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "datasets>=5.0.0",
    "diffusers>=0.39.0",
    "matplotlib>=3.11.0",
    "modal>=1.5.1",
    "onnxruntime>=1.28.0",
    "onnxscript>=0.7.1",
    "torch>=2.13.0",
    "torchvision>=0.28.0",
    "wandb>=0.28.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
